{{- if eq ( include "minecraft-proxy.createVelocitySecret" . ) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "lib.labels.common" . | nindent 4 }}
  name: {{ include "lib.secrets.name" ( dict "suffix" "velocity" "ctx" . ) }}
data:
  forwarding-key: {{ randBytes 12 | b64enc | quote }}
{{- end -}}
