{{- if eq ( include "minecraft-server.createRcloneSecret" . ) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "lib.labels.common" . | nindent 4 }}
  name: {{ include "lib.names.fullname" . }}-rclone
data:
  rclone-conf: {{ include "lib.utils.toYaml" ( dict "obj" .Values.backup.config.rcloneConfig ) | b64enc | quote }}
{{- end }}
