{{- if eq ( include "minecraft-server.createResticSecret" . ) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "lib.labels.common" . | nindent 4 }}
  name: {{ include "lib.names.fullname" . }}-restic
data:
  password: {{ .Values.backup.config.resticPassword | b64enc | quote }}
{{- end }}
